version: '3.8'

services:
  frontend:
    build:
      context: ./hr-next
      dockerfile: Dockerfile # Pastikan ada Dockerfile di dalam folder hr-next
    container_name: hr-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped