"""fix education to text and add karyawan

Revision ID: c64987a4d604
Revises: 
Create Date: 2026-02-22 23:28:37.963095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c64987a4d604'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_status', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('driver_license', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('university', sa.String(length=150), nullable=True),
    sa.Column('major', sa.String(length=150), nullable=True),
    sa.Column('gpa', sa.String(length=10), nullable=True),
    sa.Column('social_media', sa.Text(), nullable=True),
    sa.Column('position_applied', sa.String(length=100), nullable=True),
    sa.Column('last_company', sa.String(length=150), nullable=True),
    sa.Column('last_position', sa.String(length=150), nullable=True),
    sa.Column('last_position_level', sa.String(length=100), nullable=True),
    sa.Column('last_company_field', sa.String(length=100), nullable=True),
    sa.Column('total_experience_years', sa.String(length=50), nullable=True),
    sa.Column('experience_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birth_place', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('driver_license', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('university', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('gpa', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('social_media', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('position_applied', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('last_position', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('last_position_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_company_field', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('experience_description', sa.Text(), nullable=True))
        batch_op.alter_column('resume_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('education',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('total_experience_years',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('candidates_resume_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('candidates_resume_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('certifications')
        batch_op.drop_column('skills')
        batch_op.drop_column('current_role')
        batch_op.drop_column('phone')
        batch_op.drop_column('experience')
        batch_op.drop_column('languages')
        batch_op.drop_column('name')
        batch_op.drop_column('dob')
        batch_op.drop_column('social_links')
        batch_op.drop_column('summary')

    with op.batch_alter_table('test_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(), nullable=True))
        batch_op.alter_column('candidate_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['employee_id'])
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('candidate_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('candidates_resume_id_fkey'), 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('candidates_resume_id_key'), ['resume_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('total_experience_years',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('education',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('resume_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('experience_description')
        batch_op.drop_column('last_company_field')
        batch_op.drop_column('last_position_level')
        batch_op.drop_column('last_position')
        batch_op.drop_column('last_company')
        batch_op.drop_column('position_applied')
        batch_op.drop_column('social_media')
        batch_op.drop_column('gpa')
        batch_op.drop_column('major')
        batch_op.drop_column('university')
        batch_op.drop_column('province')
        batch_op.drop_column('driver_license')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('religion')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))

    op.drop_table('employees')
    # ### end Alembic commands ###
